# 🧪 Pipeline de Datos – Ingesta y Transformación

## 🎯 Objetivo
En este laboratorio desarrollarás un pipeline básico de datos que incluye:

- Ingesta de datos desde una fuente
- Limpieza de datos
- Transformación de datos
- Generación de un dataset final listo para análisis

---

## 🧠 Contexto del Caso

Una empresa de ventas necesita analizar sus transacciones, pero los datos presentan múltiples problemas:

- Datos duplicados
- Valores nulos
- Formatos inconsistentes
- Errores en los datos

Tu misión será preparar estos datos para su uso en análisis o modelos de IA.

# 📂 Paso 1: Cargar dataset
A continuación cargaremos el dataset original de transacciones de tarjetas de crédito, que contiene posibles fraudes y errores intencionales.

Antes de ejecutar, asegúrate de tener el archivo:

📄 02_fraudTest.csv

en la carpeta IA_Proyecto/data/raw/.

In [1]:
import logging
import os

# Crear carpetas necesarias en la raíz del proyecto
os.makedirs("../logs", exist_ok=True)
os.makedirs("../data/raw", exist_ok=True)
os.makedirs("../data/processed", exist_ok=True)

log_path = "../logs/ingest.log"
logging.basicConfig(
    filename=log_path,
    filemode='w',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S',
    force=True
)

# El archivo debe existir en data/raw antes de continuar
ruta_dataset = "../data/raw/02_fraudTest.csv"

if os.path.exists(ruta_dataset):
    logging.info("Dataset encontrado correctamente en data/raw")
    print("Ingesta completada")
else:
    mensaje = f"No se encontró el archivo esperado: {ruta_dataset}"
    logging.error(mensaje)
    print(mensaje)

Ingesta completada

In [2]:
import pandas as pd

logging.info(f"Inicio de carga del dataset desde ../data/raw/02_fraudTest.csv")
df = pd.read_csv("../data/raw/02_fraudTest.csv")
logging.info(f"Dataset cargado correctamente: filas={len(df)}, columnas={len(df.columns)}")

df.head()

C:\Users\nicol\AppData\Local\Temp\ipykernel_11384\3677116431.py:4: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/02_fraudTest.csv")

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,119106,fecha_invalida,377895991033232,"fraud_Bahringer, Schoen and Corkery",shopping_pos,1.07,Kimberly,Myers,F,6881 King Isle Suite 228,...,41.4682,-72.5751,5438,"Librarian, academic",1964-11-17,cf581d75ccc9ba838a05dec8bfa78b5b,1375430128,41.240083,-71.837788,0
1,179292,fecha_invalida,30364087349027,"fraud_Romaguera, Wehner and Tromp",kids_pets,94.99,Samuel,Sandoval,M,0005 Morrison Land,...,35.8896,-96.0887,7163,Fitness centre manager,1982-02-05,b1bfaf13224da41f422db483fd810dd7,1377266716,35.156537,-95.806648,0
2,540729,fecha_invalida,30328384440870,fraud_Berge-Hills,kids_pets,31.28,Helen,Campbell,F,182 Sergio Summit Apt. 129,...,40.0290,-93.1607,602,Cytogeneticist,1954-07-14,cde9fc0136873645778d0ad8817db655,1388247749,39.888665,-93.106804,0
3,374360,fecha_invalida,30364087349027,"fraud_Connelly, Reichert and Fritsch",gas_transport,73.06,Samuel,Sandoval,M,0005 Morrison Land,...,35.8896,-96.0887,7163,Fitness centre manager,1982-02-05,90b8429191e5c83df1afba4e5db4d61e,1384425890,36.734101,-96.737345,0
4,314574,fecha_invalida,4198470814557,fraud_Kuphal-Predovic,misc_net,9.99,Christie,Williamson,F,519 Jerry Views,...,41.4768,-95.3509,2036,Engineering geologist,1971-08-20,e4893795b6b3e41667129b9ed13b9650,1382147409,40.922072,-94.899388,0

# 🔍 Paso 2: Exploración inicial
Analiza el dataset y responde:

- ¿Hay valores nulos?
- ¿Existen duplicados?
- ¿Hay datos inconsistentes?
- ¿Hay errores en tipos de datos?

Ejecuta las siguientes celdas para explorar el dataset de transacciones de tarjetas de crédito.

In [3]:
logging.info(f"Exploración inicial iniciada: filas={len(df)}, columnas={len(df.columns)}")
df.info()  # Información general del dataset
logging.info("Se ejecutó df.info() para revisar tipos y nulos")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             60000 non-null  int64
 1   trans_date_trans_time  60000 non-null  object
 2   cc_num                 60000 non-null  int64
 3   merchant               60000 non-null  object
 4   category               60000 non-null  object
 5   amt                    60000 non-null  object
 6   first                  60000 non-null  object
 7   last                   60000 non-null  object
 8   gender                 60000 non-null  object
 9   street                 60000 non-null  object
 10  city                   60000 non-null  object
 11  state                  60000 non-null  object
 12  zip                    60000 non-null  int64
 13  lat                    60000 non-null  float64
 14  long                   60000 non-null  float64
 15  city_pop               60000 non-null  int64
 16  job                    60000 non-null  object
 17  dob                    60000 non-null  object
 18  trans_num              60000 non-null  object
 19  unix_time              60000 non-null  int64
 20  merch_lat              60000 non-null  float64
 21  merch_long             60000 non-null  float64
 22  is_fraud               60000 non-null  int64
dtypes: float64(4), int64(6), object(13)
memory usage: 10.5+ MB

In [4]:
nulos_totales = int(df.isnull().sum().sum())
logging.info(f"Conteo de valores nulos completado: nulos_totales={nulos_totales}")
df.isnull().sum()  # Conteo de valores nulos por columna

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [5]:
duplicados = int(df.duplicated().sum())
logging.info(f"Conteo de filas duplicadas completado: duplicados={duplicados}")
df.duplicated().sum()  # Conteo de filas duplicadas

np.int64(0)

# 🧹 Paso 3: Limpieza de datos
En este paso verificaremos y corregiremos los tipos de datos clave, y buscaremos valores inconsistentes en el dataset de transacciones de tarjetas de crédito.

- Convertir columnas de fecha y monto a su tipo correcto
- Verificar que los valores sean válidos (ejemplo: montos positivos, género válido, etc.)

In [6]:
# Conversión de tipos de datos y chequeo de valores inconsistentes
import numpy as np

# Convertir columnas de fecha
df['dob'] = pd.to_datetime(df['dob'], errors='coerce')
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'], errors='coerce')

# Convertir monto a numérico
df['amt'] = pd.to_numeric(df['amt'], errors='coerce')

# Verificar montos negativos
montos_negativos = int((df['amt'] < 0).sum())
logging.info(
    f"Limpieza completada: montos_negativos={montos_negativos}, fecha_nulas={int(df['dob'].isna().sum() + df['trans_date_trans_time'].isna().sum())}"
)
print('Transacciones con monto negativo:', montos_negativos)

# Verificar género válido
print('Valores únicos en género:', df['gender'].unique())

# Mostrar resumen de tipos de datos y primeras filas
print(df.dtypes)
df.head()

Transacciones con monto negativo: 225
Valores únicos en género: ['F' 'M' 'X']
Unnamed: 0                        int64
trans_date_trans_time    datetime64[ns]
cc_num                            int64
merchant                         object
category                         object
amt                             float64
first                            object
last                             object
gender                           object
street                           object
city                             object
state                            object
zip                               int64
lat                             float64
long                            float64
city_pop                          int64
job                              object
dob                      datetime64[ns]
trans_num                        object
unix_time                         int64
merch_lat                       float64
merch_long                      float64
is_fraud                          int64
dtype: object

C:\Users\nicol\AppData\Local\Temp\ipykernel_11384\932865174.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'], errors='coerce')

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,119106,NaT,377895991033232,"fraud_Bahringer, Schoen and Corkery",shopping_pos,1.07,Kimberly,Myers,F,6881 King Isle Suite 228,...,41.4682,-72.5751,5438,"Librarian, academic",1964-11-17,cf581d75ccc9ba838a05dec8bfa78b5b,1375430128,41.240083,-71.837788,0
1,179292,NaT,30364087349027,"fraud_Romaguera, Wehner and Tromp",kids_pets,94.99,Samuel,Sandoval,M,0005 Morrison Land,...,35.8896,-96.0887,7163,Fitness centre manager,1982-02-05,b1bfaf13224da41f422db483fd810dd7,1377266716,35.156537,-95.806648,0
2,540729,NaT,30328384440870,fraud_Berge-Hills,kids_pets,31.28,Helen,Campbell,F,182 Sergio Summit Apt. 129,...,40.0290,-93.1607,602,Cytogeneticist,1954-07-14,cde9fc0136873645778d0ad8817db655,1388247749,39.888665,-93.106804,0
3,374360,NaT,30364087349027,"fraud_Connelly, Reichert and Fritsch",gas_transport,73.06,Samuel,Sandoval,M,0005 Morrison Land,...,35.8896,-96.0887,7163,Fitness centre manager,1982-02-05,90b8429191e5c83df1afba4e5db4d61e,1384425890,36.734101,-96.737345,0
4,314574,NaT,4198470814557,fraud_Kuphal-Predovic,misc_net,9.99,Christie,Williamson,F,519 Jerry Views,...,41.4768,-95.3509,2036,Engineering geologist,1971-08-20,e4893795b6b3e41667129b9ed13b9650,1382147409,40.922072,-94.899388,0

# 🔄 Paso 4: Corrección y transformación de tipos de datos
En este paso, nos aseguraremos de que las columnas clave tengan el tipo de dato correcto y crearemos nuevas variables útiles para el análisis de fraude.

- Confirmar que las fechas y montos están correctamente convertidos
- Crear variables adicionales si es necesario (por ejemplo, año de la transacción, edad del titular, etc.)

In [7]:
# Confirmar tipos y crear variables adicionales
import pandas as pd
import numpy as np

# Confirmar tipos
print(df.dtypes)

# Crear columna: año de la transacción
df['trans_year'] = df['trans_date_trans_time'].dt.year

# Crear columna: edad del titular al momento de la transacción
df['edad'] = df['trans_date_trans_time'].dt.year - df['dob'].dt.year

logging.info(
    f"Transformación completada: trans_year y edad creadas; edad_min={df['edad'].min()}, edad_max={df['edad'].max()}"
)

# Mostrar primeras filas para verificar
df[['trans_date_trans_time', 'dob', 'trans_year', 'edad']].head()

Unnamed: 0                        int64
trans_date_trans_time    datetime64[ns]
cc_num                            int64
merchant                         object
category                         object
amt                             float64
first                            object
last                             object
gender                           object
street                           object
city                             object
state                            object
zip                               int64
lat                             float64
long                            float64
city_pop                          int64
job                              object
dob                      datetime64[ns]
trans_num                        object
unix_time                         int64
merch_lat                       float64
merch_long                      float64
is_fraud                          int64
dtype: object

  trans_date_trans_time        dob  trans_year  edad
0                   NaT 1964-11-17         NaN   NaN
1                   NaT 1982-02-05         NaN   NaN
2                   NaT 1954-07-14         NaN   NaN
3                   NaT 1982-02-05         NaN   NaN
4                   NaT 1971-08-20         NaN   NaN

# ⚙️ Paso 5: Transformación de datos
En este paso, puedes crear variables adicionales que sean relevantes para el análisis de fraude, por ejemplo:
- Diferencia de ubicación entre el titular y el comercio (distancia geográfica)
- Variables categóricas a numéricas (one-hot encoding, si es necesario para modelos)
- Otras transformaciones que faciliten el análisis o modelado

In [8]:

df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,trans_year,edad
0,119106,NaT,377895991033232,"fraud_Bahringer, Schoen and Corkery",shopping_pos,1.07,Kimberly,Myers,F,6881 King Isle Suite 228,...,5438,"Librarian, academic",1964-11-17,cf581d75ccc9ba838a05dec8bfa78b5b,1375430128,41.240083,-71.837788,0,NaN,NaN
1,179292,NaT,30364087349027,"fraud_Romaguera, Wehner and Tromp",kids_pets,94.99,Samuel,Sandoval,M,0005 Morrison Land,...,7163,Fitness centre manager,1982-02-05,b1bfaf13224da41f422db483fd810dd7,1377266716,35.156537,-95.806648,0,NaN,NaN
2,540729,NaT,30328384440870,fraud_Berge-Hills,kids_pets,31.28,Helen,Campbell,F,182 Sergio Summit Apt. 129,...,602,Cytogeneticist,1954-07-14,cde9fc0136873645778d0ad8817db655,1388247749,39.888665,-93.106804,0,NaN,NaN
3,374360,NaT,30364087349027,"fraud_Connelly, Reichert and Fritsch",gas_transport,73.06,Samuel,Sandoval,M,0005 Morrison Land,...,7163,Fitness centre manager,1982-02-05,90b8429191e5c83df1afba4e5db4d61e,1384425890,36.734101,-96.737345,0,NaN,NaN
4,314574,NaT,4198470814557,fraud_Kuphal-Predovic,misc_net,9.99,Christie,Williamson,F,519 Jerry Views,...,2036,Engineering geologist,1971-08-20,e4893795b6b3e41667129b9ed13b9650,1382147409,40.922072,-94.899388,0,NaN,NaN

# 💾 Paso 6: Guardar dataset limpio

El dataset final será almacenado para su uso posterior.

In [9]:
# Guardar el dataset limpio para su uso posterior
output_path = "../data/processed/fraude_clean.csv"
df.to_csv(output_path, index=False)
logging.info(f"Dataset limpio guardado en {output_path} con filas={len(df)} y columnas={len(df.columns)}")
print(f"Dataset limpio guardado correctamente en {output_path}")

Dataset limpio guardado correctamente en ../data/processed/fraude_clean.csv

# 📊 Paso 7: Reflexión final

Responde las siguientes preguntas:

1. ¿Qué problemas tenía el dataset original?
2. ¿Qué decisiones tomaste para limpiar los datos?
3. ¿Qué impacto tendría NO limpiar los datos?
4. ¿Qué otras transformaciones podrías aplicar?

---

## 🚀 Conclusión

Has construido un pipeline básico de datos:

✔ Ingesta  
✔ Limpieza  
✔ Transformación  
✔ Exportación  

Este proceso es fundamental en cualquier proyecto de análisis de datos o inteligencia artificial.